import type { Metadata } from "next";
import { Readex_Pro } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/commons/header";
import Footer from "./components/commons/footer";

const fredoka = localFont({
  src: "./fonts/fredoka-one-regular.ttf",
});

const readex = Readex_Pro({
  variable: "--font-readex-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SOS Vida Animal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fredoka.className} ${readex.variable} antialiased `}>
        <div className="bg-orange-primary">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
